apiVersion: apps/v1
kind: Deployment
metadata:
  name: ohif
  namespace: kube-ops
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ohif
    spec:
      containers:
        - name: ohif
          image: ohif/viewer
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      app: ohif

---
apiVersion: v1
kind: Service
metadata:
  name: ohif
  namespace: kube-ops
  labels:
    app: ohif
spec:
  ports:
  - port: 3000
    targetPort: 80
  selector:
    app: ohif

