---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ohif-deployment
  namespace: kube-ops
spec:
  template:
    metadata:
      labels:
        app: OHIFdemo
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccount: OHIFdemo
      containers:
      - name: ohif-viewer
        image: ohif/viewer
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: web
          protocol: TCP
