apiVersion: apps/v1
kind: Deployment
metadata:
  name: ohif-deployment
  labels:
    app: OHIFdemo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: OHIFdemo
    spec:
      containers:
        - name: ohif-viewer
          image: ohif/viewer
          ports:
            - containerPort: 3000
  selector:
    matchLabels:
      app: OHIFdemo
