apiVersion: apps/v1
kind: Deployment
metadata:
  name: ohif-deployment
  labels:
    app: OHIFdemo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: OHIFdemo
    spec:
      containers:
        - name: ohif-viewer
          image: ohif/viewer
          ports:
            - containerPort: 3000
  selector:
    matchLabels:
      app: OHIFdemo

---
apiVersion: v1
kind: Service
metadata:
  name: ohif-service
spec:
  selector:
    app: OHIFdemo
  type: NodePort
   ports:
     - protocol: TCP
       port: 3001
       targetPort: 3000
       nodePort: 30390
