apiVersion: apps/v1
kind: Deployment
metadata:
  name: ohif
  namespace: kube-ops
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ohif
    spec:
      containers:
        - name: ohif
          image: ohif/viewer
          ports:
            - containerPort: 3000
  selector:
    matchLabels:
      app: ohif

---
apiVersion: v1
kind: Service
metadata:
  name: ohif
  namespace: kube-ops
  labels:
    app: ohif
spec:
  selector:
    app: ohif
  type: NodePort
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3000
      nodePort: 30390
