apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demoApp
    spec:
      containers:
        - name: ohif-container
          image: ohif/viewer
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      app: demoApp
