---
apiVersion: v1
kind: Service
metadata:
  name: ohif-service
  namespace: kube-ops
  labels:
    app: ohif
spec:
  selector:
    app: ohif
  type: NodePort
  ports:
  - name: web
    port: 3000
    targetPort: web
    nodePort: 30010
